# Generated by ChatGPT, https://chatgpt.com/c/6a3579e3-88d4-83ed-ba1a-88fd058015b6

#' Collapse a call or expression to one line
#'
#' Internal helper used for compact stack printing and matching.
#'
#' @param x Object passed to [deparse()].
#'
#' @return A character scalar.
#'
#' @keywords internal
deparse_one <- function(x) 
{
	paste(deparse(x, nlines = 1L), collapse = "")
}

#' Capture the R-visible warning stack
#'
#' Builds a data frame from the active R call stack. When a warning condition is
#' supplied and `trim = "condition"`, the stack is trimmed at the condition call.
#'
#' @param w A warning condition, usually received by a `withCallingHandlers()`
#'   warning handler. If `NULL`, no condition-call trimming is done.
#' @param trim Character scalar. `"condition"` trims the stack at
#'   [conditionCall()]. `"none"` returns the full R-visible stack.
#'
#' @return A data frame with columns `frame`, `package`, `fun`, and `call`.
#'
#' @keywords internal
warning_stack <- function(w = NULL, trim = c("condition", "none")) 
{
	trim <- match.arg(trim)

	calls <- sys.calls()

	rows <- lapply(seq_along(calls), function(i) {
		fn <- tryCatch(sys.function(i), error = function(e) NULL)
		call <- calls[[i]]

		env <- if (is.function(fn)) {
			environment(fn)
		} else {
			NULL
		}

		package <- if (!is.null(env)) {
			environmentName(env)
		} else {
			NA_character_
		}

		if (!nzchar(package)) {
			package <- NA_character_
		}

		fun <- if (is.call(call) && length(call) >= 1L) {
			deparse_one(call[[1L]])
		} else {
			NA_character_
		}

		data.frame(
			frame = i,
			package = package,
			fun = fun,
			call = deparse_one(call),
			stringsAsFactors = FALSE
		)
	})

	st <- do.call(rbind, rows)

	if (identical(trim, "condition") && !is.null(w)) {
		cc <- conditionCall(w)

		if (!is.null(cc)) {
			hit <- which(vapply(
				calls,
				function(x) identical(deparse_one(x), deparse_one(cc)),
				logical(1L)
			))

			if (length(hit) > 0L) {
				st <- st[seq_len(max(hit)), , drop = FALSE]
			}
		}
	}

	st
}

#' Inspect warnings and their call stacks
#'
#' Runs an expression and prints diagnostic information for each warning:
#' the warning message, condition call, and R-visible call stack. Warnings are
#' not suppressed.
#'
#' @param expr Expression to evaluate.
#' @param stack Character scalar. `"condition"` prints the stack only up to the
#'   warning's [conditionCall()]. `"full"` prints the full R-visible stack,
#'   including handler internals.
#'
#' @return The value of `expr`, invisibly if `expr` returns invisibly. Called for
#'   its warning diagnostics side effect.
#'
#' @examples
#' f <- function() {
#' 	warning("f warned")
#' }
#'
#' inspect_warnings(f(), stack = "condition")
#'
#' @export
inspect_warnings <- function(expr, stack = c("condition", "full")) 
{
	stack <- match.arg(stack)

	withCallingHandlers(
		expr,
		warning = function(w) {
			cat("\n--- warning inspection ---\n")
			cat("message: ", conditionMessage(w), "\n", sep = "")

			cc <- conditionCall(w)
			if (!is.null(cc)) {
				cat("condition call: ", deparse_one(cc), "\n", sep = "")
			}

			st <- warning_stack(
				w,
				trim = if (identical(stack, "full")) "none" else "condition"
			)

			print(st, row.names = FALSE)
			cat("--- end inspection ---\n\n")
		}
	)
}

#' Suppress specific warnings by message and stack
#'
#' Runs an expression and suppresses only warnings that match all supplied
#' criteria. Criteria may include warning text and whether the trimmed warning
#' stack contains a package/environment name or function name.
#'
#' @param expr Expression to evaluate.
#' @param message Optional character pattern matched against [conditionMessage()].
#'   If `NULL`, the warning message is not checked.
#' @param fun Optional function name that must appear in the trimmed warning
#'   stack. If `NULL`, the stack function name is not checked.
#' @param package Optional package or environment name that must appear in the
#'   trimmed warning stack, for example `"Matrix"` or `"R_GlobalEnv"`.
#'   If `NULL`, the stack package/environment is not checked.
#' @param fixed Logical scalar passed to [grepl()]. Use `TRUE` for literal
#'   message matching and `FALSE` for regular expressions.
#'
#' @return The value of `expr`, with matching warnings suppressed.
#'
#' @details
#' The stack is trimmed at the warning's [conditionCall()] before matching.
#' If all filters are `NULL`, this suppresses all warnings from `expr`.
#'
#' If both \code{fun} and \code{package} arguments are supplied, they must match at the same frame of the stack.
#'
#' @examples
#' f <- function() {
#' 	warning("f warned")
#' }
#'
#' suppress_warnings_from(
#' 	f(),
#' 	message = "f warned",
#' 	package = "R_GlobalEnv",
#' 	fun = "f"
#' )
#'
#' @export
suppress_warnings_from <- function(
	expr,
	message = NULL,
	fun = NULL,
	package = NULL,
	fixed = TRUE
) 
{
	if (!is.null(package) && (!is.character(package) || length(package) != 1L)) {
		stop("`package` must be NULL or a single string.", call. = FALSE)
	}

	if (!is.null(fun) && (!is.character(fun) || length(fun) != 1L)) {
		stop("`fun` must be NULL or a single string.", call. = FALSE)
	}

	withCallingHandlers(
		expr,
		warning = function(w) {
			msg_ok <- is.null(message) ||
				grepl(message, conditionMessage(w), fixed = fixed)

			st <- warning_stack(w, trim = "condition")

			stack_ok <- any(vapply(seq_len(nrow(st)), function(i) {
				pkg_ok <- is.null(package) ||
					!is.na(st$package[i]) && st$package[i] == package

				fun_ok <- is.null(fun) ||
					!is.na(st$fun[i]) && st$fun[i] == fun

				pkg_ok && fun_ok
			}, logical(1L)))

			if (msg_ok && stack_ok) {
				tryInvokeRestart("muffleWarning")
			}			
		}
	)
}
